
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= $block->escapeHtml(__('Filter By')) ?></strong>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if (count($block->getLayer()->getState()->getFilters()) > 1) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                        <span title="Clear all"><i class="fa-regular fa-trash-can"></i></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
        <?php if (!$wrapOptions) : ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"></strong>
            <dl class="filter-options" id="narrow-by-list">
                <?php
                $wrapOptions = true;
                endif;
                ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <dt role="heading" aria-level="3" class="filter-options-title">
                        <?= $block->escapeHtml(__($filter->getName())) ?>
                    </dt>
                    <dd class="filter-options-content">
                        <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>
                    </dd>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions) : ?>
            </dl>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
