<a rel="nofollow" onclick="javascript:void(0);" id="gototop">
    <span class="gt-arrow">
        <i class="fa-solid fa-arrow-up"></i>
    </span>
    <span class="gt-text">
        <?= __(' Top') ?>
    </span>
</a>

<script type="text/javascript">
    require(['jquery', 'domReady!'], function($) {
        let $button = $('#gototop');
        function GoToTop() {
            if ($(this).scrollTop() > 300) {
                $button.fadeIn();
            } else {
                $button.fadeOut();
            }
        }
        new GoToTop();
        $(window).scroll(GoToTop);
        $button.on('click touch', function() {
            $('body,html').animate({scrollTop:0}, 500);
            return false;
        })
    });
</script>
