<?php

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()) : ?>
    <a href="#"
       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
       class="use-ajax action towishlist action-towishlist">
        <span title="Move to Wishlist"><?= $block->escapeHtml(__('Save for later')) ?></span>
    </a>
<?php endif ?>
