<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()) : ?>
    <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart">
        <span title="<?= $block->escapeHtml(__('Add All to Cart')) ?>">
            <i class="fa-solid fa-cart-arrow-down"></i>
        </span>
    </button>
<?php endif;?>
