<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php

/** @var \Magento\Wishlist\Block\Share\Wishlist $block */
$columns = $block->getColumns();
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

?>

<div class="products-grid wishlist">
    <?php if (count($block->getItems())) : ?>
        <table class="table data wishlist" id="wishlist-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Wish List')) ?></caption>
            <thead>
            <tr>
                <th class="col image" scope="col"><?= $block->escapeHtml(__('')) ?></th>
                <th class="col product" scope="col"><?= $block->escapeHtml(__('Product')) ?></th>
                <th class="col price" scope="col"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col comment desktop" scope="col"><?= $block->escapeHtml(__('Comment')) ?></th>
                <th class="col qty desktop" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col actions" scope="col"><?= $block->escapeHtml(__('Actions')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getWishlistItems() as $item) : ?>
                <?php
                $product = $item->getProduct();
                $isVisibleProduct = $product->isVisibleInSiteVisibility();
                ?>
                <tr class="wishlist-table-row">
                    <td data-th="<?= $block->escapeHtmlAttr(__('Image')) ?>" class="col image">
                        <a class="product photo" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                           title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
                            <?= $block->getImage($product, 'customer_shared_wishlist')->toHtml() ?>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="col product">
                        <strong class="product name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                                <?= $block->escapeHtml($product->getName()) ?>
                            </a>
                        </strong>
                        <?= $block->getDetailsHtml($item) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>" class="col price">
                        <?=
                        $block->getProductPriceHtml(
                            $product,
                            'wishlist_configured_price',
                            \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                            ['item' => $item]
                        );
                        ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="col comment desktop">
                        <div class="field comment-box">
                            <div class="control">
                                <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>" placeholder="<?= $block->escapeHtml(trim("Notes")) ?>" name="description[<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment" <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>><?= ($item->getDescription() !== null ? $block->escapeHtml($item->getDescription()) : "") ?></textarea>
                            </div>
                        </div>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="col qty desktop" data-role="add-to-links">
                        <span class="wishlist-column-qty"><?= (int) $item->getQty() ?></span>
                        <a class="action edit" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
                            <span title="<?= $block->escapeHtml(__('Edit')) ?>">
                                <i class="fa-solid fa-gear"></i>
                            </span>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="col actions"
                        data-role="add-to-links">
                        <?php if ($product->isSaleable()): ?>
                            <?php if ($isVisibleProduct): ?>
                                <button type="button"
                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                        data-post='<?= /* @noEscape */ $block->getSharedItemAddToCartUrl($item) ?>'
                                        class="action primary tocart">
                                    <span><i class="fa-solid fa-cart-plus"></i></span>
                                </button>
                            <?php endif ?>
                        <?php endif; ?>
                        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                            'onclick',
                            "location.assign(this.href); event.preventDefault();",
                            'a#wishlist-shared-item-' . $item->getId()
                        ) ?>
                        <a href="#" data-role="remove" data-post-remove='<?= /* @noEscape */ $block->getItemRemoveParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
                            <span class="remove-item-x""><i class="fa-solid fa-xmark"></i></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php else : ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>
